version: '3.4'

services:

  eventbus:
    image: rabbitmq:management

  rediscache:
    image: redis:latest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
      
  posts.api:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: Services/Posts/Posts.API/Dockerfile
      
  comments.api:
    image: ${DOCKER_REGISTRY-}commentsapi
    build:
      context: .
      dockerfile: Services/Comments/Comments.API/Dockerfile
      
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: Services/Accounts/Accounts.API/Dockerfile
      
  files.api:
    image: ${DOCKER_REGISTRY-}filesapi
    build:
      context: .
      dockerfile: Services/Files/Dockerfile

  aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: Gateway/Aggregator/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateway/ApiGateway/Dockerfile
      
  blogplatform.ui:
    image: ${DOCKER_REGISTRY-}blogplatformui
    build:
      context: .
      dockerfile: Presentation/BlogPlatform.UI/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/Identity/IdentityServer/Dockerfile

volumes:
  sqlserver-data:
  elasticsearch-data:
