version: '3.4'

services:

  eventbus:
    container_name: eventbus
    restart: always
    ports:
      - 15671:15671
      - 15672:15672
        
  rediscache:
    container_name: rediscache
    restart: always
    ports:
      - 6379:6379
        
  sqlserver:
    container_name: sqlserver
    environment:
      - MSSQL_SA_PASSWORD=1Q2w3e4r
      - ACCEPT_EULA=Y
    restart: always
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - 14330:1433
      
  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - 9200:9200
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data   

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - 5601:5601

  posts.api:
    container_name: posts.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings:LocalSqlServer=Server=sqlserver;Database=BlogPlatform_Posts;User=sa;Password=1Q2w3e4r;
      - IdentityUrl=http://identityserver
      - Redis=rediscache:6379
      - ElasticSearch=http://elasticsearch:9200
      - EventBusUrl=amqp://guest:guest@eventbus:5672
    depends_on:
      - sqlserver
      - rediscache
      - eventbus
      - elasticsearch
    ports:
      - 8000:80
      - 8005:8080
      - 18000:443
    volumes:
      - ~/.aspnet/https:/https:ro

  comments.api:
    container_name: comments.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings:LocalSqlServer=Server=sqlserver;Database=BlogPlatform_Comments;User=sa;Password=1Q2w3e4r;
      - IdentityUrl=http://identityserver
      - ElasticSearch=http://elasticsearch:9200
      - EventBusUrl=amqp://guest:guest@eventbus:5672
    depends_on:
      - sqlserver
      - eventbus
      - elasticsearch
    ports:
      - 8001:80
      - 8006:8080
      - 18001:443
    volumes:
      - ~/.aspnet/https:/https:ro

  accounts.api:
    container_name: accounts.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings:LocalSqlServer=Server=sqlserver;Database=BlogPlatform_Accounts;User=sa;Password=1Q2w3e4r;
      - IdentityUrl=http://identityserver
      - ElasticSearch=http://elasticsearch:9200
    depends_on:
      - sqlserver
      - eventbus
      - elasticsearch
    ports:
      - 8002:80
      - 18002:443
    volumes:
      - ~/.aspnet/https:/https:ro

  files.api:
    container_name: files.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - IdentityUrl=http://identityserver
      - ElasticSearch=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 8003:80
      - 18003:443
    volumes:
      - ~/.aspnet/https:/https:ro

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings:LocalSqlServer=Server=sqlserver;Database=BlogPlatform_Identity;User=sa;Password=1Q2w3e4r;
      - ClientUrl=http://localhost:8020
      - IssuerUrl=http://localhost:8008
      - ElasticSearch=http://elasticsearch:9200
    depends_on:
      - sqlserver
      - elasticsearch
    ports:
      - 8008:80
      - 18008:443
    volumes:
      - ~/.aspnet/https:/https:ro

  aggregator:
    container_name: aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - IdentityUrl=http://identityserver
      - GrpcSettings:PostsUrl=http://posts.api:8080
      - GrpcSettings:CommentsUrl=http://comments.api:8080
      - ElasticSearch=http://elasticsearch:9200
    depends_on:
      - posts.api
      - comments.api
      - elasticsearch
    ports:
      - 8009:80
      - 18009:443
    volumes:
      - ~/.aspnet/https:/https:ro

  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - IdentityUrl=http://identityserver
      - ElasticSearch=http://elasticsearch:9200
    depends_on:
      - posts.api
      - comments.api
      - accounts.api
      - files.api
      - identityserver
      - aggregator
      - elasticsearch
    ports:
      - 8010:80
      - 18010:443
    volumes:
      - ~/.aspnet/https:/https:ro

  blogplatform.ui:
    container_name: blogplatform.ui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ApiGateway=http://apigateway
      - IdentityUrl=http://identityserver
      - IssuerUrl=http://localhost:8008
      - ElasticSearch=http://elasticsearch:9200
    depends_on:
      - apigateway
      - elasticsearch
    ports:
      - 8020:80
      - 18020:443
    volumes:
      - ~/.aspnet/https:/https:ro
